name: Build Windows Portable EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install pyinstaller gdown

      # ⭐ 新增：自动下载预训练模型到 model_pretrained/
      - name: Download pretrained model
        shell: bash
        run: |
          mkdir -p model_pretrained
          # 官方 README 给出的 DocScanner-L 文件夹链接（Google Drive）
          # gdown 支持 --folder，直接把整个文件夹拉到 model_pretrained/
          gdown --fuzzy --folder "https://drive.google.com/drive/folders/1W1_DJU8dfEh6FqDYqFQ7ypR38Z8c5r4D" -O model_pretrained
          ls -lah model_pretrained

      - name: Verify model exists
        shell: bash
        run: |
          if [ ! -d "model_pretrained" ] || [ -z "$(ls -A model_pretrained)" ]; then
            echo "模型下载失败：model_pretrained 为空"
            exit 1
          fi

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile ^
            --name DocScanner ^
            --add-data "model_pretrained;model_pretrained" ^
            --add-data "inference.py;." ^
            --add-data "distorted;distorted" ^
            --add-data "rectified;rectified" ^
            --add-data "app;app" ^
            --hidden-import torch ^
            app/main.py

      - name: Package portable zip
        run: |
          mkdir DocScanner-Portable
          copy dist\\DocScanner.exe DocScanner-Portable\\
          echo Double-click DocScanner.exe to start. > DocScanner-Portable\\README.txt
          powershell -command "Compress-Archive -Path DocScanner-Portable\\* -DestinationPath DocScanner-Portable.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DocScanner-Portable
          path: DocScanner-Portable.zip
