name: Build Windows Portable EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # CPU 版 PyTorch：最通用、朋友无需装 CUDA
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install pyinstaller gdown

      # ⭐ 自动下载预训练模型到 model_pretrained/
      - name: Download pretrained model (DocScanner-L)
        shell: bash
        run: |
          mkdir -p model_pretrained
          # 采用官方 README 提供的 Google Drive 文件夹链接（可替换为你自己的镜像）
          gdown --fuzzy --folder "https://drive.google.com/drive/folders/1W1_DJU8dfEh6FqDYqFQ7ypR38Z8c5r4D" -O model_pretrained
          ls -lah model_pretrained

      - name: Verify model exists
        shell: bash
        run: |
          if [ ! -d "model_pretrained" ] || [ -z "$(ls -A model_pretrained)" ]; then
            echo "模型下载失败：model_pretrained 为空"
            exit 1
          fi

      # 确保有空目录，避免 --add-data 出错
      - name: Prepare empty runtime dirs
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path distorted | Out-Null
          New-Item -ItemType Directory -Force -Path rectified | Out-Null

      # ✅ 用 cmd 壳，续行符使用 ^
      - name: Build EXE with PyInstaller
        shell: cmd
        run: |
          pyinstaller --noconfirm --onefile ^
            --name DocScanner ^
            --add-data "model_pretrained;model_pretrained" ^
            --add-data "inference.py;." ^
            --add-data "distorted;distorted" ^
            --add-data "rectified;rectified" ^
            --add-data "app;app" ^
            --hidden-import torch ^
            app/main.py

      - name: Package portable zip
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path DocScanner-Portable | Out-Null
          Copy-Item dist\DocScanner.exe DocScanner-Portable\
          Set-Content -Path DocScanner-Portable\README.txt -Value "Double-click DocScanner.exe to start."
          Compress-Archive -Path DocScanner-Portable\* -DestinationPath DocScanner-Portable.zip -Force

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DocScanner-Portable
          path: DocScanner-Portable.zip
